### ISSUE TITLE
WestJR.get_stations実行時のValidationError

### ISSUE THREAD

**Issue by midorichaan** [unyacat/westjr#44]
## 概要
WestJR.get_stations 実行時にValidationErrorが発生する

## 再現手順
```py
import westjr

jrw = westjr.WestJR()
print(jrw.get_stations(line="osakaloop")) 
```

## 発生したエラー
```py
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 403, in __get_result        
    raise self._exception
  File "<console>", line 1, in <module>
  File "C:\Users\midori\IdeaProjects\async-westjr\westjr\api.py", line 64, in _request
    return model.parse_obj(data)
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Stations
stations -> 0 -> design -> upside -> 0 -> line
  none is not an allowed value (type=type_error.none.not_allowed)
stations -> 18 -> design -> downside -> 0 -> line
  none is not an allowed value (type=type_error.none.not_allowed)
```

## 期待する動作
get_stationsでStationsが返る

## 動作環境
OS: Windows 11 Home
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Lib: 0.4

**Comment by midorichaan** [comment]
## 追記 1 
特定の路線のみエラーが発生する....?
Ex: osakaloop
