### ISSUE TITLE
pydantic_core._pydantic_core.ValidationError: 145 validation errors for Stations

### ISSUE THREAD

**Issue by JamesXiaoMo** [unyacat/westjr#99]
```py
import westjr
jr = westjr.WestJR(line='sanyo1', area='okayama')

print(jr.get_stations())
```

```Traceback (most recent call last):
  File "/Users/.../Desktop/JRWest/main.py", line 4, in <module>
    print(jr.get_stations())
  File "/Users/.../Desktop/JRWest/.venv/lib/python3.10/site-packages/westjr/api.py", line 76, in get_stations
    return self._request(endpoint=endpoint, model=Stations)
  File "/Users/.../Desktop/JRWest/.venv/lib/python3.10/site-packages/westjr/api.py", line 46, in _request
    return model.model_validate(res.json())
  File "/Users/.../Desktop/JRWest/.venv/lib/python3.10/site-packages/pydantic/main.py", line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 145 validation errors for Stations
stations.0.info.line
  Field required [type=missing, input_value={'name': '上郡', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.0.info.pairDisplay
  Field required [type=missing, input_value={'name': '上郡', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.0.info.lines
  Field required [type=missing, input_value={'name': '上郡', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.0.design.upside.0.line
  Field required [type=missing, input_value={'type': 98, 'side': None...colorCode': 'kka-sanyo'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.0.design.upside.0.linkDirection
  Field required [type=missing, input_value={'type': 98, 'side': None...colorCode': 'kka-sanyo'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.1.info.line
  Field required [type=missing, input_value={'name': '三石', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.1.info.pairDisplay
  Field required [type=missing, input_value={'name': '三石', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.1.info.lines
  Field required [type=missing, input_value={'name': '三石', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.2.info.line
  Field required [type=missing, input_value={'name': '吉永', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.2.info.pairDisplay
  Field required [type=missing, input_value={'name': '吉永', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.2.info.lines
  Field required [type=missing, input_value={'name': '吉永', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.3.info.line
  Field required [type=missing, input_value={'name': '和気', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.3.info.pairDisplay
  Field required [type=missing, input_value={'name': '和気', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.3.info.lines
  Field required [type=missing, input_value={'name': '和気', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.4.info.line
  Field required [type=missing, input_value={'name': '熊山', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.4.info.pairDisplay
  Field required [type=missing, input_value={'name': '熊山', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.4.info.lines
  Field required [type=missing, input_value={'name': '熊山', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.5.info.line
  Field required [type=missing, input_value={'name': '万富', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.5.info.pairDisplay
  Field required [type=missing, input_value={'name': '万富', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.5.info.lines
  Field required [type=missing, input_value={'name': '万富', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.6.info.line
  Field required [type=missing, input_value={'name': '瀬戸', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.6.info.pairDisplay
  Field required [type=missing, input_value={'name': '瀬戸', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.6.info.lines
  Field required [type=missing, input_value={'name': '瀬戸', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.7.info.line
  Field required [type=missing, input_value={'name': '上道', 'code'...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.7.info.pairDisplay
  Field required [type=missing, input_value={'name': '上道', 'code'...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.7.info.lines
  Field required [type=missing, input_value={'name': '上道', 'code'...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.8.info.line
  Field required [type=missing, input_value={'name': '東岡山', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.8.info.pairDisplay
  Field required [type=missing, input_value={'name': '東岡山', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.8.info.lines
  Field required [type=missing, input_value={'name': '東岡山', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.8.design.upside.0.line
  Field required [type=missing, input_value={'type': 2, 'side': 1, 'l...73', 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.8.design.upside.0.linkDirection
  Field required [type=missing, input_value={'type': 2, 'side': 1, 'l...73', 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.8.design.downside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.8.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.9.info.line
  Field required [type=missing, input_value={'name': '高島', 'code'...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.9.info.pairDisplay
  Field required [type=missing, input_value={'name': '高島', 'code'...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.9.info.lines
  Field required [type=missing, input_value={'name': '高島', 'code'...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.9.design.upside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.9.design.upside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.9.design.downside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.9.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.9.design.downside.1.line
  Field required [type=missing, input_value={'type': 61, 'side': None...None, 'colorCode': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.9.design.downside.1.linkDirection
  Field required [type=missing, input_value={'type': 61, 'side': None...None, 'colorCode': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.10.info.line
  Field required [type=missing, input_value={'name': '西川原', 'co...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.10.info.pairDisplay
  Field required [type=missing, input_value={'name': '西川原', 'co...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.10.info.lines
  Field required [type=missing, input_value={'name': '西川原', 'co...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.10.design.upside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.10.design.upside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.10.design.upside.1.line
  Field required [type=missing, input_value={'type': 61, 'side': None...None, 'colorCode': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.10.design.upside.1.linkDirection
  Field required [type=missing, input_value={'type': 61, 'side': None...None, 'colorCode': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.10.design.downside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.10.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.info.line
  Field required [type=missing, input_value={'name': '岡山', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.info.pairDisplay
  Field required [type=missing, input_value={'name': '岡山', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.info.lines
  Field required [type=missing, input_value={'name': '岡山', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.design.upside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.design.upside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 1, 'l...one, 'colorCode': 'okn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.design.downside.0.line
  Field required [type=missing, input_value={'type': 0, 'side': None,...one, 'colorCode': 'okw'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 0, 'side': None,...one, 'colorCode': 'okw'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.design.downside.1.line
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.design.downside.1.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.design.downside.2.line
  Field required [type=missing, input_value={'type': 2, 'side': 1, 'l...46', 'colorCode': 'okm'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.11.design.downside.2.linkDirection
  Field required [type=missing, input_value={'type': 2, 'side': 1, 'l...46', 'colorCode': 'okm'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.12.info.line
  Field required [type=missing, input_value={'name': '北長瀬', 'co...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.12.info.pairDisplay
  Field required [type=missing, input_value={'name': '北長瀬', 'co...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.12.info.lines
  Field required [type=missing, input_value={'name': '北長瀬', 'co...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.12.design.upside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.12.design.upside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.12.design.downside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.12.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.13.info.line
  Field required [type=missing, input_value={'name': '庭瀬', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.13.info.pairDisplay
  Field required [type=missing, input_value={'name': '庭瀬', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.13.info.lines
  Field required [type=missing, input_value={'name': '庭瀬', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.13.design.upside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.13.design.upside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.13.design.downside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.13.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.14.info.line
  Field required [type=missing, input_value={'name': '中庄', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.14.info.pairDisplay
  Field required [type=missing, input_value={'name': '中庄', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.14.info.lines
  Field required [type=missing, input_value={'name': '中庄', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.14.design.upside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.14.design.upside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.14.design.downside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.14.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.15.info.line
  Field required [type=missing, input_value={'name': '倉敷', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.15.info.pairDisplay
  Field required [type=missing, input_value={'name': '倉敷', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.15.info.lines
  Field required [type=missing, input_value={'name': '倉敷', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.15.design.upside.0.line
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.15.design.upside.0.linkDirection
  Field required [type=missing, input_value={'type': 1, 'side': 0, 'l...one, 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.15.design.downside.0.line
  Field required [type=missing, input_value={'type': 2, 'side': 0, 'l...76', 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.15.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 2, 'side': 0, 'l...76', 'colorCode': 'okv'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.16.info.line
  Field required [type=missing, input_value={'name': '西阿知', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.16.info.pairDisplay
  Field required [type=missing, input_value={'name': '西阿知', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.16.info.lines
  Field required [type=missing, input_value={'name': '西阿知', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.17.info.line
  Field required [type=missing, input_value={'name': '新倉敷', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.17.info.pairDisplay
  Field required [type=missing, input_value={'name': '新倉敷', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.17.info.lines
  Field required [type=missing, input_value={'name': '新倉敷', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.18.info.line
  Field required [type=missing, input_value={'name': '金光', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.18.info.pairDisplay
  Field required [type=missing, input_value={'name': '金光', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.18.info.lines
  Field required [type=missing, input_value={'name': '金光', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.19.info.line
  Field required [type=missing, input_value={'name': '鴨方', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.19.info.pairDisplay
  Field required [type=missing, input_value={'name': '鴨方', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.19.info.lines
  Field required [type=missing, input_value={'name': '鴨方', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.20.info.line
  Field required [type=missing, input_value={'name': '里庄', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.20.info.pairDisplay
  Field required [type=missing, input_value={'name': '里庄', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.20.info.lines
  Field required [type=missing, input_value={'name': '里庄', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.21.info.line
  Field required [type=missing, input_value={'name': '笠岡', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.21.info.pairDisplay
  Field required [type=missing, input_value={'name': '笠岡', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.21.info.lines
  Field required [type=missing, input_value={'name': '笠岡', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.22.info.line
  Field required [type=missing, input_value={'name': '大門', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.22.info.pairDisplay
  Field required [type=missing, input_value={'name': '大門', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.22.info.lines
  Field required [type=missing, input_value={'name': '大門', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.23.info.line
  Field required [type=missing, input_value={'name': '東福山', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.23.info.pairDisplay
  Field required [type=missing, input_value={'name': '東福山', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.23.info.lines
  Field required [type=missing, input_value={'name': '東福山', 'co...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.24.info.line
  Field required [type=missing, input_value={'name': '福山', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.24.info.pairDisplay
  Field required [type=missing, input_value={'name': '福山', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.24.info.lines
  Field required [type=missing, input_value={'name': '福山', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.24.design.downside.0.line
  Field required [type=missing, input_value={'type': 2, 'side': 0, 'l...'colorCode': 'okz_pale'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.24.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 2, 'side': 0, 'l...'colorCode': 'okz_pale'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.24.design.downside.1.line
  Field required [type=missing, input_value={'type': 0, 'side': None,...one, 'colorCode': 'okx'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.24.design.downside.1.linkDirection
  Field required [type=missing, input_value={'type': 0, 'side': None,...one, 'colorCode': 'okx'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.25.info.line
  Field required [type=missing, input_value={'name': '備後赤坂', ...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.25.info.pairDisplay
  Field required [type=missing, input_value={'name': '備後赤坂', ...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.25.info.lines
  Field required [type=missing, input_value={'name': '備後赤坂', ...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.26.info.line
  Field required [type=missing, input_value={'name': '松永', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.26.info.pairDisplay
  Field required [type=missing, input_value={'name': '松永', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.26.info.lines
  Field required [type=missing, input_value={'name': '松永', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.27.info.line
  Field required [type=missing, input_value={'name': '東尾道', 'co...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.27.info.pairDisplay
  Field required [type=missing, input_value={'name': '東尾道', 'co...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.27.info.lines
  Field required [type=missing, input_value={'name': '東尾道', 'co...ます'], 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.28.info.line
  Field required [type=missing, input_value={'name': '尾道', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.28.info.pairDisplay
  Field required [type=missing, input_value={'name': '尾道', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.28.info.lines
  Field required [type=missing, input_value={'name': '尾道', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.29.info.line
  Field required [type=missing, input_value={'name': '糸崎', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.29.info.pairDisplay
  Field required [type=missing, input_value={'name': '糸崎', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.29.info.lines
  Field required [type=missing, input_value={'name': '糸崎', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.29.design.downside.0.line
  Field required [type=missing, input_value={'type': 0, 'side': None,...one, 'colorCode': 'hyg'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.29.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 0, 'side': None,...one, 'colorCode': 'hyg'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.30.info.line
  Field required [type=missing, input_value={'name': '三原', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.30.info.pairDisplay
  Field required [type=missing, input_value={'name': '三原', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.30.info.lines
  Field required [type=missing, input_value={'name': '三原', 'code'...es': None, 'end': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.30.design.downside.0.line
  Field required [type=missing, input_value={'type': 98, 'side': 0, '...08', 'colorCode': 'hyg'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.30.design.downside.0.linkDirection
  Field required [type=missing, input_value={'type': 98, 'side': 0, '...08', 'colorCode': 'hyg'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.30.design.downside.1.line
  Field required [type=missing, input_value={'type': 98, 'side': 1, '...73', 'colorCode': 'hyy'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
stations.30.design.downside.1.linkDirection
  Field required [type=missing, input_value={'type': 98, 'side': 1, '...73', 'colorCode': 'hyy'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing```

It seems the python program already have a json result,somehow it gets errors.

**Comment by eggplants** [comment]
@JamesXiaoMo You should use code block like this:

```py
import westjr
jr = westjr.WestJR(line='sanyo1', area='okayama')

print(jr.get_stations())
```


```
Traceback (most recent call last):
File ...
```
![Screenshot_2024-08-02-23-32-58-55_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/user-attachments/assets/2c6e11ad-f775-4982-8f74-d053a9fca559)

**Comment by JamesXiaoMo** [comment]
I'm a newbie at programming,thanks to tell me how to write code block.
Well, right now I'm doing a project which need to use West JR Info,since West JR didn't support a official API.I would like to use your API in my project's backend(By the way,your project is very cool,I like it).So can you fix this bug for me please.

**Comment by eggplants** [comment]
@JamesXiaoMo you can update your previous comment.
![Screenshot_2024-08-03-16-04-13-17_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/user-attachments/assets/7d1d088d-2db8-4f22-bb0f-c799fcee0369)

**Comment by unyacat** [comment]
Thank you very much for your report. @JamesXiaoMo

**Comment by unyacat** [comment]
sanyo1(に限らないかもしれませんが)、微妙に応答が違うんですね...
nicknameに `null` と `""` が存在するの最高だと思います。

![image](https://github.com/user-attachments/assets/de9e9324-9ff8-4f60-9fac-3d60a27b6bca)

**Comment by unyacat** [comment]
nickname、Listにもなりうるのか・・・

https://www.train-guide.westjr.co.jp/api/v3/sanyo1.json
```
    {
      "no": "5032M",
      "pos": "0272_####",
      "direction": 0,
      "nickname": [
        "サンライズ瀬戸・出雲"
      ],
      "type": "14",
      "displayType": "寝台",
      "dest": "東京",
      "delayMinutes": 3,
      "notice": null
    },
```

--- 

https://www.train-guide.westjr.co.jp/api/v3/kobesanyo.json
```
    {
      "no": "2085M",
      "pos": "0415_####",
      "direction": 1,
      "nickname": "くろしお３５号",
      "type": "01",
      "displayType": "特急",
      "dest": {
        "text": "和歌山",
        "code": "3709",
        "line": "hanwa"
      },
      "via": "",
      "delayMinutes": 0,
      "aSeatInfo": "",
      "typeChange": "",
      "numberOfCars": 9
    },
```

**Comment by JamesXiaoMo** [comment]
@unyacat そうなんだ。 ご回答ありがとうございました。 そうなると完全に直すのは難しいかもしれませんね。 私のプロジェクトでは山陽本線しか使っていないので、プログラムをすべてpythonでリファクタリングしようと思います。 とても助かります。誠にありがとうございました。
https://www.wuyungang.net/schoolbustime
これが私のプロジェクトのURLです。次のバージョンがリリースされたら、「westjr」に感謝の意を表します。

**Comment by unyacat** [comment]
@JamesXiaoMo Very nice application!
We will solve this problem.
The comments in Japanese are my complaint to the API provider.
